import { PrismaClient } from "@prisma/client";
import { createHmac } from "crypto";
const db = new PrismaClient();
const secret = "estimateiq-dev-secret-change-me";
const user = await db.user.findUnique({ where: { email: "demo@estimateiq.app" } });
const q = await db.question.findFirst({ where: { externalId: "umbrellas-mumbai" } });
const attempt = await db.attempt.create({ data: { userId: user.id, questionId: q.id, mode: "interviewer", status: "in_progress" } });
const payload = `${user.id}.${Date.now()}`;
const sig = createHmac("sha256", secret).update(payload).digest("hex");
console.log(JSON.stringify({ attemptId: attempt.id, cookie: `eq_session=${payload}.${sig}` }));
await db.$disconnect();
